In [16]:
xy='x1 = 46, y1 = 44 x2 = 55, y2 = 45 x3 = 56, y3 = 54\
x4 = 76, y4 = 71 x5 = 82, y5 = 82 x6 = 49, y6 = 52 x7 = 41, y7 = 36 x8 = 58, y8 = 66 x9 = 88, y9 = 86\
x10 = 82, y10 = 89 x11 = 35, y11 = 32 x12 = 79, y12 = 78 x13 = 75, y13 = 82 x14 = 36, y14 = 39\
x15 = 68, y15 = 68 x16 = 40, y16 = 30 x17 = 52, y17 = 56 x18 = 49, y18 = 49 x19 = 77, y19 = 86\
x20 = 32, y20 = 44 x21 = 89, y21 = 84 x22 = 43, y22 = 48 x23 = 89, y23 = 90 x24 = 95, y24 = 85\
x25 = 89, y25 = 79'

In [17]:
import numpy as np

In [18]:
sample=np.array(list(map(lambda x: (int(x[0].split('=')[1]), int(x[1].split('=')[1])), list(map(lambda x: x.split(','), xy.split('x')))[1:])))

In [19]:
sample

array([[46, 44],
       [55, 45],
       [56, 54],
       [76, 71],
       [82, 82],
       [49, 52],
       [41, 36],
       [58, 66],
       [88, 86],
       [82, 89],
       [35, 32],
       [79, 78],
       [75, 82],
       [36, 39],
       [68, 68],
       [40, 30],
       [52, 56],
       [49, 49],
       [77, 86],
       [32, 44],
       [89, 84],
       [43, 48],
       [89, 90],
       [95, 85],
       [89, 79]])

In [20]:
mask = sample > 0
sample[mask[:, 0] & mask[:, 1]]

array([[46, 44],
       [55, 45],
       [56, 54],
       [76, 71],
       [82, 82],
       [49, 52],
       [41, 36],
       [58, 66],
       [88, 86],
       [82, 89],
       [35, 32],
       [79, 78],
       [75, 82],
       [36, 39],
       [68, 68],
       [40, 30],
       [52, 56],
       [49, 49],
       [77, 86],
       [32, 44],
       [89, 84],
       [43, 48],
       [89, 90],
       [95, 85],
       [89, 79]])

In [21]:
x,y =sample[mask[:, 0] & mask[:, 1]].T
x,y

(array([46, 55, 56, 76, 82, 49, 41, 58, 88, 82, 35, 79, 75, 36, 68, 40, 52,
        49, 77, 32, 89, 43, 89, 95, 89]),
 array([44, 45, 54, 71, 82, 52, 36, 66, 86, 89, 32, 78, 82, 39, 68, 30, 56,
        49, 86, 44, 84, 48, 90, 85, 79]))

In [22]:
np.cov(x,y,ddof=1)[0][1]

392.375

In [23]:
np.corrcoef(x,y)[0][1]

0.9524172053928188

In [9]:
from scipy.stats import multivariate_normal
mu = np.array([0., 1.])
Sigma = np.array([[ 1. , -0.5], [-0.5,  1.5]])
W= multivariate_normal(mu, Sigma)
sample=W.rvs(size=1000)
sample

array([[-1.9944772 ,  2.05342855],
       [ 0.307309  , -0.50941497],
       [-0.11098817,  3.67612044],
       ...,
       [-2.10590585,  0.72181851],
       [-1.30676021, -0.65717439],
       [-0.66137456,  0.90090156]])

In [10]:
data='4,193; 3,998; 5,62; 4,677; 4,571; 3,26; 4,221; 4,998; 4,379; 4,632; 3,266; 3,286; 4,062; 4,336; 4,089;\
5,079; 2,979; 4,379; 4,724; 4,168; 4,595; 3,348; 3,549; 4,037; 4,372'

In [11]:
data='4,193; 3,998; 5,62; 4,677; 4,571; 3,26; 4,221; 4,998; 4,379; 4,632; 3,266; 3,286; 4,062; 4,336; 4,089;\
5,079; 2,979; 4,379; 4,724; 4,168; 4,595; 3,348; 3,549; 4,037; 4,372'
data

'4,193; 3,998; 5,62; 4,677; 4,571; 3,26; 4,221; 4,998; 4,379; 4,632; 3,266; 3,286; 4,062; 4,336; 4,089;5,079; 2,979; 4,379; 4,724; 4,168; 4,595; 3,348; 3,549; 4,037; 4,372'

In [24]:
data='0,594; 1,441; 1,668; 1,083; 0,894; 0,393; 1,884; 1,5; -0,181; 2,159; 0,48; 1,074; 0,76; 0,758; 1,049; -0,7;\
1,335; 1,036; 0,86; 2,296; 0,325; -0,889; -0,882; 1,497; -0,497; 0,477; 1,297; -2,654; 1,487; -0,191; -0,063; 0,861;\
-1,421; 1,353; -0,914'

In [25]:
def fmt(data):
    a=data.replace(',','.')
    b=a.split(';')
    c=np.array(list(map(float, list(b))))
    return c

In [26]:
x=fmt(data)# Применяем функцию fmt, которая преобразует строку данных в массив данных
x

array([ 0.594,  1.441,  1.668,  1.083,  0.894,  0.393,  1.884,  1.5  ,
       -0.181,  2.159,  0.48 ,  1.074,  0.76 ,  0.758,  1.049, -0.7  ,
        1.335,  1.036,  0.86 ,  2.296,  0.325, -0.889, -0.882,  1.497,
       -0.497,  0.477,  1.297, -2.654,  1.487, -0.191, -0.063,  0.861,
       -1.421,  1.353, -0.914])

In [27]:
x.mean()

0.5762571428571428