In [51]:
import numpy as np

1) Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.load_txt. Выведите на экран первые 5 строк массива.

In [52]:
data = np.loadtxt('./src/tables/minutes_n_ingredients2.csv',
                  delimiter=',', skiprows=1, dtype=np.int32)

data[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [162911,     60,     14]])

2) Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [53]:
from statistics import median


l_data = data[:, 1:]
print(
    l_data.mean(axis=0),
    l_data.min(axis=0),
    l_data.max(axis=0),
    np.median(l_data, axis=0),
    sep='\n'
)

[2.1601398e+04 9.0552800e+00]
[0 1]
[2147483647         39]
[40.  9.]


3) Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля  q0.75

In [54]:
time = data[:, 1]
q075 = np.quantile(time, 0.75)
time.clip(max=q075, out=time)


array([60, 25, 10, ..., 65,  5, 65])

4) Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [55]:
print(time[time == 0].shape[0])
time[time==0] = 1

479


5) Посчитайте, сколько уникальных рецептов находится в датасете.

In [56]:
np.unique(data[:, 0]).shape[0]

98252

6) Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [57]:
ingred = np.unique(data[:, 2])
print(ingred.shape[0])
print(ingred)


37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7) Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [58]:
data_ing_le_5 = data[data[:, 2] <= 5]
data_ing_le_5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [380915,      5,      4]])

8) Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [59]:
(data[:, 2] / data[:, 1]).max()

24.0

9) Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [61]:
data[data[:, 1].argsort()][:, 2][-100:].mean()

9.75

10) Выберите случайным образом и выведите информацию о 10 различных рецептах

In [64]:
data[np.random.randint(data.shape[0], size=10)]

array([[ 20312,     65,      8],
       [388215,     12,      5],
       [308069,     60,     11],
       [136590,     25,      4],
       [436554,     23,     13],
       [ 44110,     65,     12],
       [102503,     65,     17],
       [ 77747,     30,      6],
       [ 63065,     15,      6],
       [  7342,     65,     11]])

11) Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [75]:
np.where(data[:, 2] < data[:, 2].mean())[0].shape[0] / data.shape[0] * 100

58.802

12) Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [152]:
easy_data = np.hstack([data, np.zeros((data.shape[0], 1), int)])
easy_data[:, 3][(easy_data[:, 1] <= 20) & (easy_data[:, 2] <= 5)] = 1
np.where(easy_data[:, 3] == 1)[0].shape[0]


9552

13) Выведите процент "простых" рецептов в датасете

In [90]:
np.where(easy_data[:, 3] == 1)[0].shape[0] / data.shape[0] * 100


9.552

14) Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [160]:
short_rec = data[data[:, 1] < 10]
norm_rec = data[(data[:, 1] > 10) & (data[:, 1] < 20)]
long_rec = data[data[:, 1] >= 20]

mx = min([short_rec.shape[0], norm_rec.shape[0], long_rec.shape[0]])
np.array([short_rec[:mx], norm_rec[:mx], long_rec[:mx]])


array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      1,      9],
        [380915,      5,      4]],

       [[ 33941,     18,      9],
        [446597,     15,      5],
        [ 81006,     12,      7],
        ...,
        [278297,     12,      7],
        [ 66980,     15,      8],
        [ 90921,     18,      8]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [162911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]])